Replaced equal sign with colon
I currently experimenting with salt, and had troubles using the pillar.exmaple of this formula because of the equal sign. Excerpt from log:

    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 12, column 9:
            bind interfaces only = yes
            ^
could not find expected ':'
  in "<unicode string>", line 13, column 9:
            interfaces = eth0
            ^